# - name : loops playbook
#   hosts: local
#   connection: local
#   tasks:
#   - name : print names
#     ansible.builtin.debug:
#      msg: "Hello {{ item }}" # item is reserved
#     loop:
#     - Ramesh
#     - suresh
#     - Ram 

- name : install packages
  hosts: local
  connection: local
  tasks:
  - name : print names
    ansible.builtin.package:
     name: {{ item }}
     state: latest
    loop:
    - nginx
    - mysql 